name: Flake

on:
  push:
    branches:
      - main
    paths:
      - flake.nix
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  update:
    name: Flake Update
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@v13

      - id: update-flake-lock
        uses: DeterminateSystems/update-flake-lock@v23
        with:
          commit-msg: 'flake: update inputs'
          pr-title: 'flake: update inputs'
          pr-labels: 'dependencies'
